domain_path: /home/chris/test-xilinx-linux-sw-only/sw/vitis/ultra96v2_platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/chris/opt/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
